/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class co_elastic_apm_agent_jvmti_JVMTIAgentAccess */

#ifndef _Included_co_elastic_apm_agent_jvmti_JVMTIAgentAccess
#define _Included_co_elastic_apm_agent_jvmti_JVMTIAgentAccess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     co_elastic_apm_agent_jvmti_JVMTIAgentAccess
 * Method:    init0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_co_elastic_apm_agent_jvmti_JVMTIAgentAccess_init0
  (JNIEnv *, jclass);

/*
 * Class:     co_elastic_apm_agent_jvmti_JVMTIAgentAccess
 * Method:    destroy0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_co_elastic_apm_agent_jvmti_JVMTIAgentAccess_destroy0
  (JNIEnv *, jclass);

/*
 * Class:     co_elastic_apm_agent_jvmti_JVMTIAgentAccess
 * Method:    getStackTrace0
 * Signature: (IIZ[J)I
 */
JNIEXPORT jint JNICALL Java_co_elastic_apm_agent_jvmti_JVMTIAgentAccess_getStackTrace0
  (JNIEnv *, jclass, jint, jint, jboolean, jlongArray);

/*
 * Class:     co_elastic_apm_agent_jvmti_JVMTIAgentAccess
 * Method:    getDeclaringClass0
 * Signature: (J)Ljava/lang/Class;
 */
JNIEXPORT jclass JNICALL Java_co_elastic_apm_agent_jvmti_JVMTIAgentAccess_getDeclaringClass0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     co_elastic_apm_agent_jvmti_JVMTIAgentAccess
 * Method:    getMethodName0
 * Signature: (JZ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_co_elastic_apm_agent_jvmti_JVMTIAgentAccess_getMethodName0
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     co_elastic_apm_agent_jvmti_JVMTIAgentAccess
 * Method:    setThreadProfilingCorrelationBuffer0
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_co_elastic_apm_agent_jvmti_JVMTIAgentAccess_setThreadProfilingCorrelationBuffer0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     co_elastic_apm_agent_jvmti_JVMTIAgentAccess
 * Method:    setProcessProfilingCorrelationBuffer0
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_co_elastic_apm_agent_jvmti_JVMTIAgentAccess_setProcessProfilingCorrelationBuffer0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     co_elastic_apm_agent_jvmti_JVMTIAgentAccess
 * Method:    createThreadProfilingCorrelationBufferAlias
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_co_elastic_apm_agent_jvmti_JVMTIAgentAccess_createThreadProfilingCorrelationBufferAlias
  (JNIEnv *, jclass, jlong);

/*
 * Class:     co_elastic_apm_agent_jvmti_JVMTIAgentAccess
 * Method:    createProcessProfilingCorrelationBufferAlias
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_co_elastic_apm_agent_jvmti_JVMTIAgentAccess_createProcessProfilingCorrelationBufferAlias
  (JNIEnv *, jclass, jlong);

/*
 * Class:     co_elastic_apm_agent_jvmti_JVMTIAgentAccess
 * Method:    startProfilerReturnChannelSocket0
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_co_elastic_apm_agent_jvmti_JVMTIAgentAccess_startProfilerReturnChannelSocket0
  (JNIEnv *, jclass, jstring);

/*
 * Class:     co_elastic_apm_agent_jvmti_JVMTIAgentAccess
 * Method:    stopProfilerReturnChannelSocket0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_co_elastic_apm_agent_jvmti_JVMTIAgentAccess_stopProfilerReturnChannelSocket0
  (JNIEnv *, jclass);

/*
 * Class:     co_elastic_apm_agent_jvmti_JVMTIAgentAccess
 * Method:    readProfilerReturnChannelSocket0
 * Signature: (Ljava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_co_elastic_apm_agent_jvmti_JVMTIAgentAccess_readProfilerReturnChannelSocket0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     co_elastic_apm_agent_jvmti_JVMTIAgentAccess
 * Method:    sendToProfilerReturnChannelSocket0
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_co_elastic_apm_agent_jvmti_JVMTIAgentAccess_sendToProfilerReturnChannelSocket0
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     co_elastic_apm_agent_jvmti_JVMTIAgentAccess
 * Method:    checkVirtualThreadMountEventSupport0
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_co_elastic_apm_agent_jvmti_JVMTIAgentAccess_checkVirtualThreadMountEventSupport0
  (JNIEnv *, jclass);

/*
 * Class:     co_elastic_apm_agent_jvmti_JVMTIAgentAccess
 * Method:    enableVirtualThreadMountEvents0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_co_elastic_apm_agent_jvmti_JVMTIAgentAccess_enableVirtualThreadMountEvents0
  (JNIEnv *, jclass);

/*
 * Class:     co_elastic_apm_agent_jvmti_JVMTIAgentAccess
 * Method:    disableVirtualThreadMountEvents0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_co_elastic_apm_agent_jvmti_JVMTIAgentAccess_disableVirtualThreadMountEvents0
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
